[book]
title = "Discovery"
description = "Discover the world of microcontrollers through Rust with the BB2 micro:bit v2"
authors = ["Rust Embedded Resources Team"]
language = "en"

[output.html]
git-repository-url = "https://github.com/rust-embedded/discovery-mb2/"

[output.epub]
